import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"

const seedDirectory = path.resolve("seed")
const output = path.resolve("supabase/seed.sql")

async function readJson(name: string) {
  return JSON.parse(await readFile(path.join(seedDirectory, name), "utf8"))
}

function quote(value: unknown) {
  return `'${JSON.stringify(value).replaceAll("'", "''")}'::jsonb`
}

function insertFromJson(table: string, columns: string[], value: unknown, conflict = "do nothing") {
  const definitions = columns.map((column) => `${column} ${column === "metadata" ? "jsonb" : "text"}`).join(", ")
  const select = columns
    .map((column) => {
      if (column === "metadata") return column
      if (["active", "verified", "is_primary", "is_closed"].includes(column)) return `${column}::boolean`
      if (["sort_order", "weekday"].includes(column)) return `${column}::integer`
      if (["id", "parent_id", "business_id", "category_id"].includes(column)) return `${column}::uuid`
      if (["trusted_since"].includes(column)) return `${column}::date`
      if (["opens_at", "closes_at"].includes(column)) return `${column}::time`
      if (["starts_at", "ends_at"].includes(column)) return `${column}::timestamptz`
      if (column === "status") return `${column}::public.business_status`
      if (column === "source") return `${column}::public.trust_signal_source`
      if (column === "type" && table === "business_media") return `${column}::public.media_type`
      if (column === "type" && table === "offerings") return `${column}::public.offering_type`
      if (column === "type" && table === "trust_signals") return `${column}::public.trust_signal_type`
      return column
    })
    .join(", ")
  return `insert into public.${table} (${columns.join(", ")})\nselect ${select} from jsonb_to_recordset(${quote(value)}) as x(${definitions})\non conflict ${conflict};\n`
}

async function main() {
  const domains = await readJson("domains.json")
  const categories = await readJson("categories.json")
  const businesses = await readJson("businesses.json")
  const relations = await readJson("business-relations.json")
  const locations = await readJson("locations.json")
  const hours = await readJson("business-hours.json")
  const media = await readJson("business-media.json")
  const offerings = await readJson("offerings.json")
  const signals = await readJson("trust-signals.json")

  const sql = [
    "-- Generated by npm run seed:sql. Development and Staging only.\n",
    "begin;\n",
    insertFromJson("domains", ["id", "name", "description", "sort_order", "active"], domains),
    insertFromJson("categories", ["id", "parent_id", "slug", "name", "description", "sort_order", "active"], categories),
    insertFromJson("businesses", ["id", "slug", "name", "description", "specialty", "phone", "whatsapp", "email", "website", "verified", "status", "trusted_since"], businesses),
    insertFromJson("category_domains", ["category_id", "domain_id"], relations.category_domains),
    insertFromJson("business_domains", ["business_id", "domain_id", "is_primary"], relations.business_domains),
    insertFromJson("business_categories", ["business_id", "category_id", "is_primary"], relations.business_categories),
    insertFromJson("locations", ["id", "business_id", "label", "city", "state_code", "neighborhood", "address_line", "postal_code", "latitude", "longitude", "service_area", "is_primary"], locations),
    insertFromJson("business_hours", ["id", "business_id", "weekday", "opens_at", "closes_at", "is_closed", "timezone"], hours),
    insertFromJson("business_media", ["id", "business_id", "type", "url", "alt_text", "sort_order"], media),
    insertFromJson("offerings", ["id", "business_id", "category_id", "type", "name", "description", "metadata", "active"], offerings),
    insertFromJson("trust_signals", ["id", "business_id", "type", "source", "active", "starts_at", "ends_at"], signals),
    "commit;\n",
  ].join("\n")

  await writeFile(output, sql, "utf8")
  console.log(`SQL de seed gerado em ${output}.`)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
